@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:

### ------------------------------------------------------------------------
# Get service info
GET {{server}}/eventmanager
{{me}}

### ------------------------------------------------------------------------

# Get $metadata document
GET {{server}}/eventmanager/$metadata

### ------------------------------------------------------------------------

# Browse Events without Participants
GET {{server}}/eventmanager/Events?
  # &$select=ID,title,descr,date
  # &$expand=Participants
  # &sap-language=de
### ------------------------------------------------------------------------

# Browse Events with Participants
GET {{server}}/eventmanager/Events?
  # &$select=ID,title,descr,date
  # &$expand=confirmedParticipants 
   &$expand=participants 
  # &sap-language=de

### ------------------------------------------------------------------------

# Browse Participants without Events (Parent node )
GET {{server}}/eventmanager/Participants?
  # &$select=ID,name
  # &$expand=parent

### ------------------------------------------------------------------------

# Browse Participants with Events (Parent node )
GET {{server}}/eventmanager/Participants?
  # &$select=ID,name
  &$expand=parent

### ------------------------------------------------------------------------
# Create Event
POST {{server}}/eventmanager/Events
Content-Type: application/json;IEEE754Compatible=true

{
  "identifier": "18",
  "title": "SAP Global All Hands",
  "description": "SAP Global All Hands in Germany",
  //"date": "2020-05-01:00:00.000Z",
  "maxParticipantsNumber": 2,
  "participantsFeeAmount": "10.00"
  //"currency": { "code": "USD" }
  //"currency_code":  "USD" 
}
### ------------------------------------------------------------------------

# Update Event
PATCH  {{server}}/eventmanager/Events(26cf90c1-b22d-4e4b-89cf-7b0dccd861c5)
Content-Type: application/json;IEEE754Compatible=true

{
  "participantsFeeAmount": "40.00"
 }
### ------------------------------------------------------------------------

# Delete Event
DELETE  {{server}}/eventmanager/Events(4d9a31aa-f1f5-4514-a990-c27ac0c9ad84)

### ------------------------------------------------------------------------

GET {{server}}/eventmanager/Events(26cf90c1-b22d-4e4b-89cf-7b0dccd861c5)
### ------------------------------------------------------------------------
# call action cancel
POST {{server}}/eventmanager/Events(26cf90c1-b22d-4e4b-89cf-7b0dccd861c5)/EventManager.cancel
Content-Type: application/json;IEEE754Compatible=true

{
    
}

### ------------------------------------------------------------------------
# call action publish
POST {{server}}/eventmanager/Events(bd98ddfe-1fa9-4a71-8a61-5d0015fa16ff)/EventManager.publish
Content-Type: application/json;IEEE754Compatible=true

{
    
}

### ------------------------------------------------------------------------
# call action block
POST {{server}}/eventmanager/Events(bd98ddfe-1fa9-4a71-8a61-5d0015fa16ff)/EventManager.block
Content-Type: application/json;IEEE754Compatible=true

{
    
}

### ------------------------------------------------------------------------
# call action complete
POST {{server}}/eventmanager/Events(bd98ddfe-1fa9-4a71-8a61-5d0015fa16ff)/EventManager.complete
Content-Type: application/json;IEEE754Compatible=true

{
    
}
### ------------------------------------------------------------------------

# Browse Events without Participants
GET {{server}}/eventmanager/Events?
  # &$select=ID,title,descr,date
  # &$expand=Participants
  # &sap-language=de
### ------------------------------------------------------------------------

### ------------------------------------------------------------------------
# Create Participant
POST {{server}}/eventmanager/Participants
Content-Type: application/json;IEEE754Compatible=true

{
  "parent_ID":"bd98ddfe-1fa9-4a71-8a61-5d0015fa16ff" ,
  "identifier": "11",
  "name": "Murthy v",
  "email": "murthy.v@sap.com",
  "mobileNumber": "+91 9945933229",
  "statusCode": 2
}

### ------------------------------------------------------------------------

# Browse Participants with Events (Parent node )
GET {{server}}/eventmanager/Participants?
  # &$select=ID,name
  &$expand=parent

### ------------------------------------------------------------------------


### ------------------------------------------------------------------------

# call action block
POST {{server}}/eventmanager/Events(0aba33af-ba7d-4467-92ac-b8f017c57a3e)/Participants(3fd4c21d-f715-4baf-9d9c-34bba8cc44ac)/Participants.cancelParticipation
Content-Type: application/json;IEEE754Compatible=true

{
    
}

### ------------------------------------------------------------------------
# call action block
GET  {{server}}/eventmanager/Participants(3fd4c21d-f715-4baf-9d9c-34bba8cc44ac)
Content-Type: application/json;IEEE754Compatible=true

{
    
}
