@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:

### ------------------------------------------------------------------------
# Get service info
GET {{server}}/eventmanager
{{me}}

### ------------------------------------------------------------------------

# Get $metadata document
GET {{server}}/eventmanager/$metadata

### ------------------------------------------------------------------------

# Browse Events without Participants
GET {{server}}/eventmanager/Events?
  # &$select=ID,title,descr,date
  # &$expand=Participants
  # &sap-language=de
### ------------------------------------------------------------------------

# Browse Events with Participants
GET {{server}}/eventmanager/Events?
  # &$select=ID,title,descr,date
  # &$expand=confirmedParticipants 
   &$expand=participants 
  # &sap-language=de

### ------------------------------------------------------------------------

# Browse Participants without Events (Parent node )
GET {{server}}/eventmanager/Participants?
  # &$select=ID,name
  # &$expand=parent

### ------------------------------------------------------------------------

# Browse Participants with Events (Parent node )
GET {{server}}/eventmanager/Participants?
  # &$select=ID,name
  &$expand=parent

### ------------------------------------------------------------------------
# Create Event
POST {{server}}/eventmanager/Events
Content-Type: application/json;IEEE754Compatible=true

{
  "identifier": "18",
  "title": "SAP Global All Hands",
  "description": "SAP Global All Hands in Germany",
  //"date": "2020-05-01:00:00.000Z",
  "maxParticipantsNumber": 2,
  "participantsFeeAmount": "10.00"
  //"currency": { "code": "USD" }
  //"currency_code":  "USD" 
}
### ------------------------------------------------------------------------

# Update Event
PATCH  {{server}}/eventmanager/Events(26cf90c1-b22d-4e4b-89cf-7b0dccd861c5)
Content-Type: application/json;IEEE754Compatible=true

{
  "participantsFeeAmount": "40.00"
 }
### ------------------------------------------------------------------------

# Delete Event
DELETE  {{server}}/eventmanager/Events(4d9a31aa-f1f5-4514-a990-c27ac0c9ad84)

### ------------------------------------------------------------------------

GET {{server}}/eventmanager/Events(26cf90c1-b22d-4e4b-89cf-7b0dccd861c5)
### ------------------------------------------------------------------------
# call action cancel
POST {{server}}/eventmanager/Events(26cf90c1-b22d-4e4b-89cf-7b0dccd861c5)/EventManager.cancel
Content-Type: application/json;IEEE754Compatible=true

{
    
}

### ------------------------------------------------------------------------
# call action publish
POST {{server}}/eventmanager/Events(e5f47e1c-e7d7-4957-8294-e51e4f9abe6c)/EventManager.publish
Content-Type: application/json;IEEE754Compatible=true

{
    
}

### ------------------------------------------------------------------------
# call action block
POST {{server}}/eventmanager/Events(bd98ddfe-1fa9-4a71-8a61-5d0015fa16ff)/EventManager.block
Content-Type: application/json;IEEE754Compatible=true

{
    
}

### ------------------------------------------------------------------------
# call action complete
POST {{server}}/eventmanager/Events(bd98ddfe-1fa9-4a71-8a61-5d0015fa16ff)/EventManager.complete
Content-Type: application/json;IEEE754Compatible=true

{
    
}
### ------------------------------------------------------------------------

# Browse Events without Participants
GET {{server}}/eventmanager/Events?
  # &$select=ID,title,descr,date
  # &$expand=Participants
  # &sap-language=de
### ------------------------------------------------------------------------

### ------------------------------------------------------------------------
# Create Participant
POST {{server}}/eventmanager/Participants
Content-Type: application/json;IEEE754Compatible=true

{
  "parent_ID":"06e877e7-7ceb-4c61-9c8f-85a3a5e00f3f" ,
  "identifier": "14",
  "name": "Murthy v",
  "email": "",
  "mobileNumber": "+49 151 5711123a",
  "statusCode": 2
}

### ------------------------------------------------------------------------

# Browse Participants with Events (Parent node )
GET {{server}}/eventmanager/Participants?
  # &$select=ID,name
  &$expand=parent

### ------------------------------------------------------------------------

GET {{server}}/eventmanager/Events(79ceab87-300d-4b66-8cc3-f82c679b77ac)/Participants(848f961c-70ec-4f9c-b23b-bb1fffee2be2)
### ------------------------------------------------------------------------

# call action block
POST {{server}}/eventmanager/Events(79ceab87-300d-4b66-8cc3-f82c679b77ac)/Participants(848f961c-70ec-4f9c-b23b-bb1fffee2be2)
Content-Type: application/json;IEEE754Compatible=true

{
    
}

### ------------------------------------------------------------------------
# call action block
POST   {{server}}/eventmanager/Participants(e03dd13e-66a6-4f87-911b-0a03dbcceaf4)/EventManager.cancelParticipation
Content-Type: application/json;IEEE754Compatible=true

{
    
}
### ------------------------------------------------------------------------

GET {{server}}/eventmanager/Participants(e03dd13e-66a6-4f87-911b-0a03dbcceaf4)
### ------------------------------------------------------------------------
# call action block
POST   {{server}}/eventmanager/Events(79ceab87-300d-4b66-8cc3-f82c679b77ab)/participants(faa6334b-854f-4050-bc4c-1839703d8ca5)/EventManager.cancelParticipation
Content-Type: application/json;IEEE754Compatible=true

{
    
}
### ------------------------------------------------------------------------

Events(79ceab87-300d-4b66-8cc3-f82c679b77ab)/participants(c3bb78dd-615f-484e-ad66-abb5f750e5db)/EventManager.cancelParticipation

### ------------------------------------------------------------------------
# call action block
POST   {{server}}/eventmanager/Events(ID=79ceab87-300d-4b66-8cc3-f82c679b77ab,IsActiveEntity=true)/participants(ID=c65661aa-578e-47e3-9804-8d7940d5a003,IsActiveEntity=true)/EventManager.cancelParticipation
Content-Type: application/json;IEEE754Compatible=true

{
    
}
### ------------------------------------------------------------------------

get {{server}}/eventmanager/Events(ID=79ceab87-300d-4b66-8cc3-f82c679b77ab,IsActiveEntity=true)/participants(ID=c65661aa-578e-47e3-9804-8d7940d5a003,IsActiveEntity=true)

### ------------------------------------------------------------------------

get {{server}}/eventmanager/Events(ID=79ceab87-300d-4b66-8cc3-f82c679b77ab,IsActiveEntity=false)/participants(ID=c65661aa-578e-47e3-9804-8d7940d5a003,IsActiveEntity=false)